# Generated by Django 3.0.2 on 2020-01-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bal',
            field=models.DecimalField(decimal_places=30, default=0.0, max_digits=40),
        ),
    ]
