# Generated by Django 2.1 on 2020-01-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectEarnings',
            new_name='ProjectEarning',
        ),
        migrations.RenameModel(
            old_name='ProjectExpenses',
            new_name='ProjectExpense',
        ),
        migrations.RenameModel(
            old_name='ProjectProfileImages',
            new_name='ProjectProfileImage',
        ),
    ]
