# Generated by Django 2.1 on 2020-02-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200131_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpense',
            name='comment',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
