# Generated by Django 2.1 on 2020-02-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20200130_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pe', 'pending'), ('co', 'complete'), ('ca', 'canceled')], max_length=1),
        ),
    ]
