# Generated by Django 3.0.2 on 2020-02-04 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('projects', '0002_auto_20200131_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.CharField(max_length=200)),
                ('profile_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectProfile')),
            ],
        ),
    ]
