# Generated by Django 3.0.2 on 2020-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=30, max_digits=40)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[(1, 'deposit'), (2, 'withdraw')], max_length=1)),
                ('status', models.CharField(choices=[(1, 'pending'), (2, 'complete'), (3, 'canceled')], max_length=1)),
            ],
        ),
    ]
