# Generated by Django 3.0.2 on 2020-01-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0002_auto_20200130_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'complete'), ('C', 'canceled')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('D', 'deposit'), ('W', 'withdraw')], max_length=1),
        ),
    ]
